### PR TITLE
added powers

### PR DESCRIPTION
**Pull request by ofsho**
and tried other shit

### CODE REVIEW

**Comment by ofsho** [comment]
made a bunch of commits but i basically added `modulus`, `powers` to the math and`findIndex`, `join` to the arrays.

**Comment by ofsho** [comment]
and changed the symbols `!=` meaning `!=` to `!=` meaning `!==` and `==` to `===`

**Comment by Rstar284** [comment]
Oh no pls not the `===` not another js :(

**Comment by ofsho** [comment]
no, in arum you write `==` it just compiles to `===`

**Comment by Just-a-Unity-Dev** [comment]
thank you

**Pull request merged**
